/*
 * MP2TS.cpp
 *
 *  Created on: Jul 12, 2015
 *      Author: lmartel
 */

#include <vector>
#include <string>

namespace MP2TS {

std::vector<std::string> gStreamTypeName {
   /* 0x00 */ "Reserved",
   /* 0x01 */ "ISO/IEC 11172-2 (MPEG-1 Video)",
   /* 0x02 */ "ITU-T Rec. H.262 and ISO/IEC 13818-2",
   /* 0x03 */ "ISO/IEC 11172-3 (MPEG-1 audio)",
   /* 0x04 */ "ISO/IEC 13818-3 (MPEG-2 halved sample rate audio)",
   /* 0x05 */ "ITU-T Rec. H.222 and ISO/IEC 13818-1 (MPEG-2 tabled data)",
   /* 0x06 */ "ITU-T Rec. H.222 and ISO/IEC 13818-1 (MPEG-2 packetized data)",
   /* 0x07 */ "ISO/IEC 13522 (MHEG)",
   /* 0x08 */ "ITU-T Rec. H.222 and ISO/IEC 13818-1 ",
   /* 0x09 */ "ITU-T Rec. H.222 and ISO/IEC 13818-1/11172-1 auxiliary data",
   /* 0x0a */ "ISO/IEC 13818-6 DSM CC multiprotocol encapsulation",
   /* 0x0b */ "ISO/IEC 13818-6 DSM CC U-N messages",
   /* 0x0c */ "ISO/IEC 13818-6 DSM CC stream descriptors",
   /* 0x0d */ "ISO/IEC 13818-6 DSM CC tabled data",
   /* 0x0e */ "ISO/IEC 13818-1 auxiliary data",
   /* 0x0f */ "ISO/IEC 13818-7 ADTS AAC (MPEG-2 lower bit-rate audio)",
   /* 0x10 */ "ISO/IEC 14496-2 (MPEG-4 H.263 based video)",
   /* 0x11 */ "ISO/IEC 14496-3 (MPEG-4 LOAS multi-format framed audio)",
   /* 0x12 */ "ISO/IEC 14496-1 (MPEG-4 FlexMux) in packetized stream",
   /* 0x13 */ "ISO/IEC 14496-1 (MPEG-4 FlexMux) in ISO/IEC 14496 tables",
   /* 0x14 */ "ISO/IEC 13818-6 DSM CC synchronized download protocol",
   /* 0x15 */ "Packetized metadata",
   /* 0x16 */ "Sectioned metadata",
   /* 0x17 */ "ISO/IEC 13818-6 DSM CC Data Carousel metadata",
   /* 0x18 */ "ISO/IEC 13818-6 DSM CC Object Carousel metadata",
   /* 0x19 */ "ISO/IEC 13818-6 Synchronized Download Protocol metadata",
   /* 0x1a */ "ISO/IEC 13818-11 IPMP",
   /* 0x1b */ "ITU-T Rec. H.264 and ISO/IEC 14496-10 (lower bit-rate video)",
   /* 0x1c */ "Warning: Unknown or Reserved Stream Type",
   /* 0x1d */ "Warning: Unknown or Reserved Stream Type",
   /* 0x1e */ "Warning: Unknown or Reserved Stream Type",
   /* 0x1f */ "Warning: Unknown or Reserved Stream Type",
   /* 0x20 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x21 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x22 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x23 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x24 */ "ITU-T Rec. H.265 and ISO/IEC 23008-2 (Ultra HD video)",
   /* 0x25 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x26 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x27 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x28 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x29 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x2a */ "Warning: Unknown or Reserved Stream Type",
   /* 0x2b */ "Warning: Unknown or Reserved Stream Type",
   /* 0x2c */ "Warning: Unknown or Reserved Stream Type",
   /* 0x2d */ "Warning: Unknown or Reserved Stream Type",
   /* 0x2e */ "Warning: Unknown or Reserved Stream Type",
   /* 0x2f */ "Warning: Unknown or Reserved Stream Type",
   /* 0x30 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x31 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x32 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x33 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x34 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x35 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x36 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x37 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x38 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x39 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x3a */ "Warning: Unknown or Reserved Stream Type",
   /* 0x3b */ "Warning: Unknown or Reserved Stream Type",
   /* 0x3c */ "Warning: Unknown or Reserved Stream Type",
   /* 0x3d */ "Warning: Unknown or Reserved Stream Type",
   /* 0x3e */ "Warning: Unknown or Reserved Stream Type",
   /* 0x3f */ "Warning: Unknown or Reserved Stream Type",
   /* 0x40 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x41 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x42 */ "Chinese Video Standard",
   /* 0x43 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x44 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x45 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x46 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x47 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x48 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x49 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x4a */ "Warning: Unknown or Reserved Stream Type",
   /* 0x4b */ "Warning: Unknown or Reserved Stream Type",
   /* 0x4c */ "Warning: Unknown or Reserved Stream Type",
   /* 0x4d */ "Warning: Unknown or Reserved Stream Type",
   /* 0x4e */ "Warning: Unknown or Reserved Stream Type",
   /* 0x4f */ "Warning: Unknown or Reserved Stream Type",
   /* 0x50 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x51 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x52 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x53 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x54 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x55 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x56 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x57 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x58 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x59 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x5a */ "Warning: Unknown or Reserved Stream Type",
   /* 0x5b */ "Warning: Unknown or Reserved Stream Type",
   /* 0x5c */ "Warning: Unknown or Reserved Stream Type",
   /* 0x5d */ "Warning: Unknown or Reserved Stream Type",
   /* 0x5e */ "Warning: Unknown or Reserved Stream Type",
   /* 0x5f */ "Warning: Unknown or Reserved Stream Type",
   /* 0x60 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x61 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x62 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x63 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x64 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x65 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x66 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x67 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x68 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x69 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x6a */ "Warning: Unknown or Reserved Stream Type",
   /* 0x6b */ "Warning: Unknown or Reserved Stream Type",
   /* 0x6c */ "Warning: Unknown or Reserved Stream Type",
   /* 0x6d */ "Warning: Unknown or Reserved Stream Type",
   /* 0x6e */ "Warning: Unknown or Reserved Stream Type",
   /* 0x6f */ "Warning: Unknown or Reserved Stream Type",
   /* 0x70 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x71 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x72 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x73 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x74 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x75 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x76 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x77 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x78 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x79 */ "Warning: Unknown or Reserved Stream Type",
   /* 0x7a */ "Warning: Unknown or Reserved Stream Type",
   /* 0x7b */ "Warning: Unknown or Reserved Stream Type",
   /* 0x7c */ "Warning: Unknown or Reserved Stream Type",
   /* 0x7d */ "Warning: Unknown or Reserved Stream Type",
   /* 0x7e */ "Warning: Unknown or Reserved Stream Type",
   /* 0x7f */ "Warning: Unknown or Reserved Stream Type",
   /* 0x80 */ "ITU-T Rec. H.262 and ISO/IEC 13818-2 for DigiCipher II or PCM audio for Blu-ray",
   /* 0x81 */ "Dolby Digital up to six channel audio for ATSC and Blu-ray",
   /* 0x82 */ "SCTE subtitle or DTS 6 channel audio for Blu-ray",
   /* 0x83 */ "Dolby TrueHD lossless audio for Blu-ray",
   /* 0x84 */ "Dolby Digital Plus up to 16 channel audio for Blu-ray",
   /* 0x85 */ "DTS 8 channel audio for Blu-ray",
   /* 0x86 */ "DTS 8 channel lossless audio for Blu-ray",
   /* 0x87 */ "Dolby Digital Plus up to 16 channel audio for ATSC",
   /* 0x88 */ "Warning: Privately defined Stream Id",
   /* 0x89 */ "Warning: Privately defined Stream Id",
   /* 0x8a */ "Warning: Privately defined Stream Id",
   /* 0x8b */ "Warning: Privately defined Stream Id",
   /* 0x8c */ "Warning: Privately defined Stream Id",
   /* 0x8d */ "Warning: Privately defined Stream Id",
   /* 0x8e */ "Warning: Privately defined Stream Id",
   /* 0x8f */ "Warning: Privately defined Stream Id",
   /* 0x90 */ "Blu-ray Presentation Graphic Stream (subtitling)",
   /* 0x91 */ "Warning: Privately defined Stream Id",
   /* 0x92 */ "Warning: Privately defined Stream Id",
   /* 0x93 */ "Warning: Privately defined Stream Id",
   /* 0x94 */ "Warning: Privately defined Stream Id",
   /* 0x95 */ "ATSC DSM CC Network Resources table",
   /* 0x96 */ "Warning: Privately defined Stream Id",
   /* 0x97 */ "Warning: Privately defined Stream Id",
   /* 0x98 */ "Warning: Privately defined Stream Id",
   /* 0x99 */ "Warning: Privately defined Stream Id",
   /* 0x9a */ "Warning: Privately defined Stream Id",
   /* 0x9b */ "Warning: Privately defined Stream Id",
   /* 0x9c */ "Warning: Privately defined Stream Id",
   /* 0x9d */ "Warning: Privately defined Stream Id",
   /* 0x9e */ "Warning: Privately defined Stream Id",
   /* 0x9f */ "Warning: Privately defined Stream Id",
   /* 0xa0 */ "Warning: Privately defined Stream Id",
   /* 0xa1 */ "Warning: Privately defined Stream Id",
   /* 0xa2 */ "Warning: Privately defined Stream Id",
   /* 0xa3 */ "Warning: Privately defined Stream Id",
   /* 0xa4 */ "Warning: Privately defined Stream Id",
   /* 0xa5 */ "Warning: Privately defined Stream Id",
   /* 0xa6 */ "Warning: Privately defined Stream Id",
   /* 0xa7 */ "Warning: Privately defined Stream Id",
   /* 0xa8 */ "Warning: Privately defined Stream Id",
   /* 0xa9 */ "Warning: Privately defined Stream Id",
   /* 0xaa */ "Warning: Privately defined Stream Id",
   /* 0xab */ "Warning: Privately defined Stream Id",
   /* 0xac */ "Warning: Privately defined Stream Id",
   /* 0xad */ "Warning: Privately defined Stream Id",
   /* 0xae */ "Warning: Privately defined Stream Id",
   /* 0xaf */ "Warning: Privately defined Stream Id",
   /* 0xb0 */ "Warning: Privately defined Stream Id",
   /* 0xb1 */ "Warning: Privately defined Stream Id",
   /* 0xb2 */ "Warning: Privately defined Stream Id",
   /* 0xb3 */ "Warning: Privately defined Stream Id",
   /* 0xb4 */ "Warning: Privately defined Stream Id",
   /* 0xb5 */ "Warning: Privately defined Stream Id",
   /* 0xb6 */ "Warning: Privately defined Stream Id",
   /* 0xb7 */ "Warning: Privately defined Stream Id",
   /* 0xb8 */ "Warning: Privately defined Stream Id",
   /* 0xb9 */ "Warning: Privately defined Stream Id",
   /* 0xba */ "Warning: Privately defined Stream Id",
   /* 0xbb */ "Warning: Privately defined Stream Id",
   /* 0xbc */ "Warning: Privately defined Stream Id",
   /* 0xbd */ "Warning: Privately defined Stream Id",
   /* 0xbe */ "Warning: Privately defined Stream Id",
   /* 0xbf */ "Warning: Privately defined Stream Id",
   /* 0xc0 */ "DigiCipher II text",
   /* 0xc1 */ "Warning: Privately defined Stream Id",
   /* 0xc2 */ "ATSC DSM CC synchronous data",
   /* 0xc3 */ "Warning: Privately defined Stream Id",
   /* 0xc4 */ "Warning: Privately defined Stream Id",
   /* 0xc5 */ "Warning: Privately defined Stream Id",
   /* 0xc6 */ "Warning: Privately defined Stream Id",
   /* 0xc7 */ "Warning: Privately defined Stream Id",
   /* 0xc8 */ "Warning: Privately defined Stream Id",
   /* 0xc9 */ "Warning: Privately defined Stream Id",
   /* 0xca */ "Warning: Privately defined Stream Id",
   /* 0xcb */ "Warning: Privately defined Stream Id",
   /* 0xcc */ "Warning: Privately defined Stream Id",
   /* 0xcd */ "Warning: Privately defined Stream Id",
   /* 0xce */ "Warning: Privately defined Stream Id",
   /* 0xcf */ "Warning: Privately defined Stream Id",
   /* 0xd0 */ "Warning: Privately defined Stream Id",
   /* 0xd1 */ "BBC Dirac (Ultra HD video)",
   /* 0xd2 */ "Warning: Privately defined Stream Id",
   /* 0xd3 */ "Warning: Privately defined Stream Id",
   /* 0xd4 */ "Warning: Privately defined Stream Id",
   /* 0xd5 */ "Warning: Privately defined Stream Id",
   /* 0xd6 */ "Warning: Privately defined Stream Id",
   /* 0xd7 */ "Warning: Privately defined Stream Id",
   /* 0xd8 */ "Warning: Privately defined Stream Id",
   /* 0xd9 */ "Warning: Privately defined Stream Id",
   /* 0xda */ "Warning: Privately defined Stream Id",
   /* 0xdb */ "Warning: Privately defined Stream Id",
   /* 0xdc */ "Warning: Privately defined Stream Id",
   /* 0xdd */ "Warning: Privately defined Stream Id",
   /* 0xde */ "Warning: Privately defined Stream Id",
   /* 0xdf */ "Warning: Privately defined Stream Id",
   /* 0xe0 */ "Warning: Privately defined Stream Id",
   /* 0xe1 */ "Warning: Privately defined Stream Id",
   /* 0xe2 */ "Warning: Privately defined Stream Id",
   /* 0xe3 */ "Warning: Privately defined Stream Id",
   /* 0xe4 */ "Warning: Privately defined Stream Id",
   /* 0xe5 */ "Warning: Privately defined Stream Id",
   /* 0xe6 */ "Warning: Privately defined Stream Id",
   /* 0xe7 */ "Warning: Privately defined Stream Id",
   /* 0xe8 */ "Warning: Privately defined Stream Id",
   /* 0xe9 */ "Warning: Privately defined Stream Id",
   /* 0xea */ "Microsoft Windows Media Video 9 (lower bit-rate video)",
   /* 0xeb */ "Warning: Privately defined Stream Id",
   /* 0xec */ "Warning: Privately defined Stream Id",
   /* 0xed */ "Warning: Privately defined Stream Id",
   /* 0xee */ "Warning: Privately defined Stream Id",
   /* 0xef */ "Warning: Privately defined Stream Id",
   /* 0xf0 */ "Warning: Privately defined Stream Id",
   /* 0xf1 */ "Warning: Privately defined Stream Id",
   /* 0xf2 */ "Warning: Privately defined Stream Id",
   /* 0xf3 */ "Warning: Privately defined Stream Id",
   /* 0xf4 */ "Warning: Privately defined Stream Id",
   /* 0xf5 */ "Warning: Privately defined Stream Id",
   /* 0xf6 */ "Warning: Privately defined Stream Id",
   /* 0xf7 */ "Warning: Privately defined Stream Id",
   /* 0xf8 */ "Warning: Privately defined Stream Id",
   /* 0xf9 */ "Warning: Privately defined Stream Id",
   /* 0xfa */ "Warning: Privately defined Stream Id",
   /* 0xfb */ "Warning: Privately defined Stream Id",
   /* 0xfc */ "Warning: Privately defined Stream Id",
   /* 0xfd */ "Warning: Privately defined Stream Id",
   /* 0xfe */ "Warning: Privately defined Stream Id",
   /* 0xff */ "Warning: Privately defined Stream Id"

};

}
